### ISSUE TITLE
AttributeError: 'ChatMessage' object has no attribute 'to_openai_format'

### ISSUE THREAD

**Issue by JunK4i** [deepset-ai/haystack-integrations#269]
haystack_integrations\tracing\langfuse\tracer.py", line 54, in set_content_tag
    messages = [m.to_openai_format() for m in value["messages"]]
                ^^^^^^^^^^^^^^^^^^
AttributeError: 'ChatMessage' object has no attribute 'to_openai_format'

Deprecated to_openai_format() is causing issues with tracer.py.
Need to update tracer.py from deprecated function to the new function

Deprecated function:
m.to_openai_format()

Update to:
from haystack.components.generators.openai_utils import _convert_message_to_openai_format
_convert_message_to_openai_format(m)

**Comment by julian-risch** [comment]
Hello @JunK4i could you please check which version of the langfuse-haystack integration you are using?

We removed the usage of the deprecated ChatMessage.to_openai_format int he following PR a month ago: https://github.com/deepset-ai/haystack-core-integrations/pull/1001 and since then released two new versions of the langfuse-haystack package https://pypi.org/project/langfuse-haystack/#history

**Comment by JunK4i** [comment]
You are right, sorry for my oversight
